// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HelloPluginClient is the client API for HelloPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloPluginClient interface {
	// Sends a greeting
	Hello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type helloPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloPluginClient(cc grpc.ClientConnInterface) HelloPluginClient {
	return &helloPluginClient{cc}
}

func (c *helloPluginClient) Hello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.HelloPlugin/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloPluginServer is the server API for HelloPlugin service.
// All implementations must embed UnimplementedHelloPluginServer
// for forward compatibility
type HelloPluginServer interface {
	// Sends a greeting
	Hello(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedHelloPluginServer()
}

// UnimplementedHelloPluginServer must be embedded to have forward compatible implementations.
type UnimplementedHelloPluginServer struct {
}

func (UnimplementedHelloPluginServer) Hello(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedHelloPluginServer) mustEmbedUnimplementedHelloPluginServer() {}

// UnsafeHelloPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloPluginServer will
// result in compilation errors.
type UnsafeHelloPluginServer interface {
	mustEmbedUnimplementedHelloPluginServer()
}

func RegisterHelloPluginServer(s grpc.ServiceRegistrar, srv HelloPluginServer) {
	s.RegisterService(&HelloPlugin_ServiceDesc, srv)
}

func _HelloPlugin_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloPluginServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HelloPlugin/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloPluginServer).Hello(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// HelloPlugin_ServiceDesc is the grpc.ServiceDesc for HelloPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelloPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.HelloPlugin",
	HandlerType: (*HelloPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _HelloPlugin_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/helloplugin.proto",
}
